## This function creates a special matrix that can cache its inverse
## The process of computing the inverse of a matrix 
## can be a costly process. Computing and caching this inverse
## may provide performance gains rather than re-computing, when needed.

makeCacheMatrix <- function(x = matrix()) {
        ## Set value of matrix
        inv <- NULL
        set <- function(y){
          x <<- y
          inv <<- NULL
        }  
        ## return the value of the matrix
        get <- function() x
        
        ## set inverse of matrix
        setInverse <- function(Inv) inv <<- Inv
        getInverse <- function() inv
        
        list(
          set = set,
          get = get,
          setInverse = setInverse,
          getInverse = getInverse
          )
}


## cacheSolve computes the inverse of a matrix generated by makeCacheMatrix() function.
## If the inverse was previously calculated and cache, the cached inverse in rather returned,
## saving computing resources.

cacheSolve <- function(x, ...) {
  ## Return a matrix that is the inverse of 'x'
  
  ## Get the inverse of the matrix
  inv <- x$getInv()
  
  ## Check for the existence of a cached inverse
  
  print("Checking for cached inverse...")
  
  if(!is.null(inv)){
    return(inv)
  }
  
  ## Otherwise, generate the inverse of the matrix
  inv <- solve(x$get())  
  x$setInv(inv)
  
  ## Return the inverse of the matrix
  return(inv)
}
